### PR TITLE
Update vkey* pngs with those from Simple_Ten_Eighty for latest Virtua…

### PR DESCRIPTION
**Pull request by original-birdman**
…lKeyboard.

### CODE REVIEW

**Comment by Huevos** [comment]
Gordon this can't be merged. It shows as a merge conflict. No idea why but the merge buttons are not available. . I think you will need to create a new branch from the tip of master and add these files to it.

**Comment by original-birdman** [comment]
Odd, giving that is what I did...
I'll have another go.

(The Conflicting files list does refer to files in Ian's second icon change.)

**Comment by original-birdman** [comment]
Even odder.
It has already been merged: https://github.com/OpenViX/skins/commit/61e89e345753fbabc22d4711b8f1dd0ff06fa376

and if I look at the current HEAD of master the vkey* files in `ViXBMC_1080_Confluence/buttons` (and `Bello`) are the same as those under `Simple_1080`, which is all I'm trying to achieve.

The clash was that https://github.com/OpenViX/skins/commit/8a9d2d2d7e95c160c244321d3de3bdf50020d8c0 removed 4 files, but they are removed in HEAD.

So all _looks_ OK.

**Comment by Huevos** [comment]
I don't know. It showed as an "open" pull request with buttons in grey and a notice saying merge conflict. Weird!

**Pull request closed without merging**
