### PR TITLE
Update Magic-HD-Night/Noire for new VirtualKeyBoard

### PR DESCRIPTION
**Pull request by IanSav**
* [Magic-HD-Night] Update VirtualKeyBoard images

    Add new images for the updated VirtualKeyBoard.

* [Magic-HD-Noire] Update VirtualKeyBoard images

    Add new images for the updated VirtualKeyBoard.

* [CommonSkin.xml] VirtualKeyBoard update

    Update skin for compatibility with the new VirtualKeyBoard.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
The png files in the defaultfallback skin are used. Do you still want this merged?

**Comment by IanSav** [comment]
The changes to the skin XML file are needed.

When I tested the new XML the images did not get loaded.  When I added the images they were found.

Can you test just the XML change and see if you experience similar results.

**Comment by AbuBaniaz** [comment]
I have tried this several times, it works without any changes.

I am presuming that the person on forum removed the fallback skin. If I rename the default skin folder, keyboard does not show.

Not a problem merging, but please be sure.

**Comment by IanSav** [comment]
Please give the merge a try.  We can always revert if there is a problem.

Given that this skin has been abandoned by the person you copied it from Rob perhaps it should be removed entirely and ask the user to move onto one of Rob's supported skins?

**Comment by AbuBaniaz** [comment]
You can't even uninstall the default skin. So was a manual removal.

It works as it is. I'll someone else decide.

IMO, we are better off making other skins same as this instead of duplication. Pity there is no 1080 default skin

**Comment by Huevos** [comment]
Sooner or later we need to get round to using SVG images.

**Comment by IanSav** [comment]
I tried to propose a multi resolution default skin.  No-one seemed interested.

**Comment by IanSav** [comment]
By the way, I have the new images in skin_default yet the Magic-HD-Night skin could not load the images.  The XML file is definitely in need of change.

**Comment by IanSav** [comment]
@Abu: Did you test the "ViX-HD-Night" skin or the "Magic-HD-Night" skin?  The problems are with "Magic-HD-Night".

**Comment by AbuBaniaz** [comment]
Ian, there is no problem. I checked Delagroov's skin.

**Comment by AbuBaniaz** [comment]
Weird, two receivers were fine, third was not. So merged it.

**Comment by IanSav** [comment]
The changes I submitted should be safe and fine even if the skin_default images are working.  :)

**Pull request merged**
